/** 事件判别联合：relay-* 事件必携带完整快照 payload（非可选） */
/** 代理策略：none=直连；from-env=读环境代理；url 形态仅 SDK 使用 */
export type HttpProxyOptions = 'none' | 'from-env' | { url: string }

/** 从 SDK 错误消息的 [<kebab-code>] 前缀派生稳定错误码（SCREAMING_SNAKE）；无前缀返回 null */
export declare function deriveErrorCode(message: string): string | null

export type FabricEventJs =
  | {
      type: 'peer-connected' | 'peer-disconnected'
      endpointId: string
    }
  | { type: 'roster-updated' }
  | { type: 'message'; from: string; data: Buffer }
  | { type: 'path-changed'; endpointId: string; status: 'direct' | 'relay' | 'unknown' }
  | { type: 'relay-online' | 'relay-offline'; relay: RelayStatusJs }

/** relay 状态快照（relayStatus() 返回值与 relay-* 事件 payload 同构） */
export interface RelayStatusJs {
  /** 字面量联合（非 string） */
  mode: 'disabled' | 'custom' | 'n0'
  /** 配置的 relay URL 列表（disabled 为空数组；n0 为 iroh 上游默认 relay
   *  列表——4 个区域节点，排序冻结；配置原样字符串，R2 P1-4/R3 P1-4） */
  urls: string[]
  /** null <=> mode === "disabled"；否则为任一 relay 已连接 */
  online: boolean | null
  /** 最近一次连接错误类别（脱敏：无凭证段；无错误为 null） */
  lastError: string | null
  /** 配置序最小的已连接 relay URL；online !== true 或 disabled 时为 null。
   *  tie-break：同时连上多个 relay 时取配置序最小者（内核 aggregate_relay_status
   *  既有 online_url 逻辑，无新语义）。 */
  activeUrl: string | null
}

/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * dweb fabric：应用级组网的 Node SDK 入口。
 * 工厂：Fabric.createRoot / Fabric.open / Fabric.attach；完成后调用 shutdown 释放资源。
 */
export declare class Fabric {
  /** 创建新 fabric（本节点成为 root，可签发邀请与撤销）。 */
  static createRoot(opts: FabricOptions, secret?: SecretSeedHandle | undefined | null): Promise<Fabric>
  /** 打开已有 fabric（数据目录已含名册）。 */
  static open(opts: FabricOptions, secret?: SecretSeedHandle | undefined | null): Promise<Fabric>
  /** 以加入者身份起步（空名册；随后调用 join 兑换邀请）。 */
  static attach(opts: FabricOptions, fabricIdHex: string, secret?: SecretSeedHandle | undefined | null): Promise<Fabric>
  /**
   *  一步加入：从令牌解析 fabric_id，attach + 兑换 + 持久化名册。
   *  令牌前置检查（解码/过期/地址规范化）先于本地数据面加载与身份句柄消费
   * （D11 冻结顺序：令牌自身错误优先于目录检查）。
   *  task 2.5：按串前缀分派前置检查——dweb2. 走 v2 precheck（附录 A 全部
   *  校验含 capability 一致性），v1 路径零变化；后续 join 由内核按同前缀
   *  分派（OK2 兑换 + member capability 持久化）。
   */
  static joinWithToken(opts: FabricOptions, token: string, secret?: SecretSeedHandle | undefined | null): Promise<Fabric>
  /** 本节点 EndpointId（z-base-32，52 字符） */
  get endpointId(): string
  /** fabric id（hex） */
  fabricIdHex(): Promise<string>
  /** 当前有效成员投影 */
  members(): Promise<Array<Member>>
  /** 查询 EndpointId 是否为有效成员 */
  isMember(endpointId: string): Promise<boolean>
  /**
   * 签发邀请令牌（root-only）。返回 dweb1. 前缀的自包含字符串。
   * 第三参 opts 透传签发安全门逃生阀：relay 为空且 advertiseAddrs 为空时，
   * 无 opts 或 allowRelayless !== true => reject（[invite-without-relay]）。
   */
  invite(ttlMs: number, recipient?: string | undefined | null, opts?: InviteOptions | undefined | null): Promise<string>
  /** 兑换邀请令牌加入 fabric（issuer-online 单次兑换）。 */
  join(token: string): Promise<void>
  /**
   * root 自签 per-relay own capability（server-access-policy task 2.3/2.5）。
   * 对 relay.relays 中带 serverId 的条目以 root 身份现签（caps 全位、
   * TTL 180d 上限内）注入本地 RelayMap；静态 token 条目原样注入。
   * 返回 (url, token) 列表供调用方转交/审计。非 root 调用报名册
   * root-only 错误（"operation requires root …"，原生变体无前缀）。
   */
  ensureRelayCapabilities(): Promise<Array<RelayCapabilityJs>>
  /** 连接成员（常规通道；双向门控 + 名册同步）。幂等（活跃连接直接成功）。 */
  connect(endpointId: string): Promise<void>
  /** 断开与某成员的会话 */
  disconnect(endpointId: string): Promise<void>
  /** 发送不透明二进制 envelope */
  send(endpointId: string, data: Buffer): Promise<void>
  /** 撤销成员（root-only）；投影收紧并断开既有会话。 */
  revoke(endpointId: string): Promise<void>
  /** 设置本节点显示名 */
  setDisplayName(name: string): Promise<void>
  /** 查询与某成员的当前路径类型："direct" | "relay" | "unknown" */
  linkStatus(endpointId: string): Promise<string>
  /**
   * relay 状态快照（零等待，读内核缓存）。快照优先于事件：初始事实一律先查
   * 本方法，事件只承载后续跳变。禁用模式 online 为 null（而非 false）。
   */
  relayStatus(): Promise<RelayStatusJs>
  /**
   * 显式导出身份（identity export，不含 roster）为 `dwebkey1.` 加密串。
   * 交由产品自行安全保存（如账号系统加密托管——密文上云、口令在用户）。
   */
  exportSecretPassphrase(passphrase: string): Promise<string>
  /**
   * 注册事件回调（可多次调用，多个回调都会收到全部事件）。
   * 返回句柄 id；off(id) 注销（index.js 包装为取消订阅函数）。
   */
  on(callback: (event: FabricEventJs) => void): () => void
  /**
   * continuity：与对端建立逻辑会话（design §3.3 唯一创建入口）。
   * 返回 SessionHandle——内建 auto-resume 驱动（断线续传对 JS 透明）。
   */
  openSession(peerId: string): Promise<SessionHandle>
  /**
   * continuity：对端连接状态快照（design §3.1；Phase 1 task 2.3 补课投影）。
   * snapshot 优先于事件；epoch/stateSeq 为 bigint。
   */
  continuitySnapshot(peerId: string): Promise<ConnectionStateSnapshotJs>
  /** continuity：注入连接死亡（故障注入面——驱动恢复语义验证；非生产用途）。 */
  continuityReset(peerId: string): Promise<void>
  /** 添加对端直连地址提示（e2e 组网：固定端口对拨）。 */
  addKnownAddr(endpointId: string, addr: string): Promise<void>
  /**
   * serveHttp：provider 侧 HTTP 引擎（design §3.4）。
   * handler 为 TSFN JSON 事件回调（native 桥形态）；§3.4 规范签名
   * （HttpHandler 类型面）见 /http 子路径胶水。
   */
  serveHttp(peerId: string, handler: ((err: Error | null, arg: string) => void)): Promise<HttpServerJs>
  /** 注销事件回调（on 返回的 id）。 */
  off(id: number): void
  /**
   * 优雅关闭：断开全部会话并释放网络资源。幂等。
   * R3 P1-1：共享完成门——只有首次调用执行 drain（内核 shutdown + 事件泵
   * abort）；并发晚到调用等待同一完成通知后返回（返回即"无后续事件"）。
   */
  shutdown(): Promise<void>
}

/**
 * fetchHttp 响应：status/headers/streamId + bodyNext（pull-first）。
 * http/index.js 胶水另注入 [Symbol.asyncIterator]（§3.4 body AsyncIterable 投影）。
 */
export declare class HttpClientResponseJs {
  get status(): number
  get headers(): Array<HeaderJs>
  /** 逻辑流 id（/http/internals 观测面；幂等键关联）。 */
  get streamId(): number
  /**
   * 拉取下一块 body（EOF = null）。pull-first：无桥内缓冲——JS 消费速度即
   * 内核 delivered 队列排空速度。并发调用经公平 Mutex 串行（offset 序保持）；
   * 会话 Dead/Closed 时有界失败。
   */
  bodyNext(): Promise<Buffer | null>
  /**
   * WS 隧道（keepOpen 请求专用）：client→provider 方向继续写。
   * 整消息边界 ABI（WsMessage，§3.4）归 Phase 4——本面是字节隧道级，如实标注。
   */
  sendTunnel(data: Buffer): Promise<void>
  /**
   * per-request 取消（幂等）：向 provider 发 RESET——serve 响应循环止付、
   * 流式 body 供给面关闭，上游 handler 提前收敛（本地断开 → 上游关闭）。
   * 通道已死时发送失败即取消目的已达，静默成功。
   */
  abort(): Promise<void>
}

/**
 * serveHttp 返回句柄：close() 停引擎循环 + 未决 handler 以取消结算。
 * 引擎 accept 循环与 per-connection dispatch 任务由内核承接；close 后残留
 * dispatch 由 wait_active 有界（30s）退出。
 */
export declare class HttpServerJs {
  /** 服务对端（观测）。 */
  get peerId(): string
  /** 是否已关闭（观测）。 */
  get closed(): boolean
  /** （内部面 /http/internals）未决 handler 请求数（在途观测）。 */
  get pendingRequestCount(): number
  /**
   * （内部面）JS handler 正常返回：status（100..=599 整数）/headers/bodyChunks
   * （静态数组；流式供给由引擎有界背压承接）。
   */
  resolveRequest(requestId: number, status: number, headers?: Array<HeaderJs> | undefined | null, bodyChunks?: Array<Buffer> | undefined | null): void
  /**
   * （内部面）流式结算：立即回状态行（响应头此刻发出——SSE 首包/WS 101
   * 早发），body 经返回的 StreamWriterJs 持续 write/finish。与
   * resolveRequest 互斥（先到者胜）。unknown id 幂等返回 null。
   */
  respondStreaming(requestId: number, status: number, headers?: Array<HeaderJs> | undefined | null): StreamWriterJs | null
  /** （内部面）JS handler 抛错/拒绝：引擎按未发头前失败处置（500）。 */
  rejectRequest(requestId: number, message: string): void
  /** （内部面）请求体拉取（pull-first；EOF = null；unknown id / 会话终态 → 错误）。 */
  requestBodyNext(requestId: number): Promise<Buffer | null>
  /**
   * 关闭（幂等）：停引擎循环 + 未决 handler 以取消结算 + 清 body 注册表。
   * 已 dispatch 流的引擎侧收尾由内核 wait_active 有界（30s）退出。
   */
  close(): Promise<void>
}

/**
 * 受保护的身份种子句柄：内部持有 [`SecretSeed`]（zeroize-on-drop），
 * 被 Fabric 构造消费（take）后即失效。用于"导入 token / 产品托管解密后"
 * 向 Fabric 注入身份而不经手明文 JS 字符串。内部 Arc：句柄可 clone 进
 * 配置对象，take 语义全局共享（一次消费）。
 */
export declare class SecretSeedHandle {
  /** 派生 EndpointId（z32 展示串；不暴露种子本体）。 */
  get endpointId(): string
  /** 是否仍持有种子（未被消费）。 */
  get available(): boolean
}

/**
 * continuity 会话句柄（design §3.3；唯一创建入口 Fabric.openSession）。
 * 内建 auto-resume 驱动——断线续传对 JS 透明；close() 走 Session 层
 * Shutdown 语义（置 Closed + abort pump + 停驱动）。
 */
export declare class SessionHandle {
  /** 对端 EndpointId（z32） */
  get peerId(): string
  /** 会话 id（hex，128bit） */
  get sessionId(): string
  /** 会话状态快照（§3.2 对齐子集；snapshot 优先——onState 只承载跳变）。 */
  state(): Promise<SessionStateSnapshotJs>
  /**
   * 订阅状态变化（native 返回回调 id；index.js 包装为取消订阅函数；
   * payload 为 §3.2 快照同构 JSON）。
   */
  onState(callback: (state: SessionStateSnapshotJs) => void): () => void
  /** 注销状态回调（onState 返回的 id）。 */
  offState(id: number): void
  /** 显式关闭（幂等）：置 Closed + abort pump + 停 auto-resume 驱动。 */
  close(): Promise<void>
  /**
   * （内部面 /net/internals）单流 journal 持有字节（观测；streamId 来自
   * 响应/内部面的逻辑流 id）。
   */
  journalBytes(streamId: number): Promise<number>
  /**
   * fetchHttp：发起 HTTP 请求（§3.4；本阶段静态 body 分块；响应 body 为
   * pull-first——bodyNext() 逐块拉取，EOF = null）。§3.4 规范签名（自由
   * 函数形态）见 /http 子路径胶水。
   */
  fetchHttp(init: FetchHttpInit): Promise<HttpClientResponseJs>
  /**
   * head 等待期外部取消（index.js 胶水由 fetchHttp request.signal 触发）：
   * 即时向对端发 RESET 清理在途请求，pending fetch 以错误结算。晚到/
   * 未知 key 为幂等 no-op。
   */
  abortFetch(abortKey: number): void
}

/**
 * 流式响应写句柄（respondStreaming 返回）：write 逐块供给（有界通道背压
 * ——消费速度传导到内核发送面）；finish 半关（EOF）。对端 RESET/引擎丢弃
 * 时 write 报错——调用方据此提前收敛上游（本地断开 → 上游关闭链路）。
 * 三态观测（0.6.0 三拆，正交）：
 * - finished：本地已调用 finish()（半关意图）
 * - cancelled：对端取消事件已触发本请求（watcher 旗）
 * - closed：底层投递通道已关（内核不再消费后续 write）
 * getter 为观测面；write 的错误返回仍为取消/关闭的真相面。
 */
export declare class StreamWriterJs {
  /** 是否已 finish（本地半关意图，幂等面）。 */
  get finished(): boolean
  /** 对端取消（RESET/会话终态遗弃）是否已触发本请求（事件驱动观测）。 */
  get cancelled(): boolean
  /** 底层投递通道是否已关（内核停止消费——完成/放弃/取消后均翻转）。 */
  get closed(): boolean
  /**
   * 写入一块 body（背压：通道满即等待——内核发送面/对端消费速度传导）。
   * finish 后写、或对端已取消（RESET/引擎丢弃）→ 错误。
   */
  write(chunk: Buffer): Promise<void>
  /** 半关（EOF；幂等）：对端随后的 bodyNext 返回 null。 */
  finish(): void
}

/**
 * continuity 连接状态快照（design §3.1；Phase 1 task 2.3 补课投影）。
 * epoch/stateSeq 按 napi 习惯映射为 number（工作区 napi 特性集为 napi4——
 * BigInt 需 napi6；f64 精确到 2^53，epoch/seq 单调计数远不及）。
 */
export interface ConnectionStateSnapshotJs {
  peerId: string
  /** "disconnected" | "connecting" | "handshaking" | "ready" | "closing" */
  phase: string
  /** 当前已采纳连接代次；0 = 尚无 */
  epoch: number
  /** 快照单调序号（跳变检测） */
  stateSeq: number
  /** "direct" | "relay" | "unknown" */
  path: string
  changedAtMs: number
  reason?: string
}

/** Fabric 构造配置 */
export interface FabricOptions {
  /** 数据目录（名册持久化位置；secret 默认实现也指向此目录） */
  dataDir: string
  relay?: RelayOptions
  /** 写入邀请令牌的 issuer 直连地址（host:port；逐项校验，非法构造 reject） */
  advertiseAddrs?: Array<string>
  /**
   * HTTP 控制面（relay 连接）代理所有权；缺省 "none"。
   * iroh endpoint 不读进程环境变量；QUIC 数据面永不经代理。
   */
  httpProxy?: HttpProxyOptions
  /** join 总时限（毫秒）；缺省 30000；值域 [1000, 600000]，越界构造 reject */
  joinTimeoutMs?: number
  /** 本端 QUIC 绑定地址（host:port；e2e 组网需要固定端口对拨时使用） */
  bindAddr?: string
}

/** fetchHttp 请求初始化（本阶段静态 body 分块；AsyncIterable body 后续 phase）。 */
export interface FetchHttpInit {
  method: string
  path: string
  headers?: Array<HeaderJs>
  body?: Array<Buffer>
  /** WS 隧道模式：不半关请求方向（101 后双向持续；配合 sendTunnel）。 */
  keepOpen?: boolean
  /** 响应头等待上限毫秒（默认 30s——长轮询/慢上游按需放宽）。 */
  headTimeoutMs?: number
  /**
   * 外部取消键（index.js 胶水由 request.signal 生成注册；abort 时经
   * SessionHandle.abortFetch(key) 触发 head 等待期即时 RESET）。
   */
  abortKey?: number
}

/** HTTP 头（数组形态保重复项，§3.4）。 */
export interface HeaderJs {
  name: string
  value: string
}


/**
 * 导入 `dwebkey1.` 身份导出串：口令派生解密，返回受保护的种子句柄。
 * （不落盘；注入 Fabric 用工厂的 secret 参数。Argon2 在阻塞线程池执行。）
 */
export declare function importSecret(token: string, passphrase: string): Promise<SecretSeedHandle>

/** invite 逃生阀选项（D3）。 */
export interface InviteOptions {
  /** 允许签发无 relay 令牌；调用方自担可达性责任（带外路径）。 */
  allowRelayless?: boolean
}

/** 成员信息 */
export interface Member {
  endpointId: string
  displayName?: string
  sinceMs: number
}

/** SDK 原生层版本 */
export declare function nativeVersion(): string

/** ensureRelayCapabilities 的返回条目（root 自签/透传的 per-relay 凭证）。 */
export interface RelayCapabilityJs {
  /** relay URL（配置原样形态） */
  url: string
  /** `dwebr1.` capability 串 */
  token: string
}

/**
 * `relay.relays` 单条条目（server-access-policy task 2.5）：per-relay
 * capability 凭证配置。`serverId` 与 `token` 二选一或全无——
 * - `serverId`：restricted relay 的 ServerId（64 hex；admin 注册 owner 时
 *   转交）——root 据此本地自签 own/bootstrap/member capability
 *   （`ensureRelayCapabilities` / v2 invite / OK2 附发）；
 * - `token`：现成 `dwebr1.` capability 串（手工/测试用），原样注入本地
 *   RelayMap（Authorization: Bearer 头）。
 * 全无 = 无凭证条目（等价旧 `urls` 形态的对应项）。
 */
export interface RelayEntryOptions {
  /** relay URL（http/https；与 urls 同规构造期校验） */
  url: string
  /** restricted relay 的 ServerId（64 hex；None = 非 restricted 条目） */
  serverId?: string
  /** 现成 dwebr1. capability 串（None = 无静态凭证） */
  token?: string
}

/** relay 配置（判别联合：非法组合构造期拒绝） */
export type RelayOptions =
  | { mode?: 'n0' }
  | { mode: 'disabled' }
  | { mode: 'custom'; urls: [string, ...string[]] }
  | { mode: 'custom'; relays: [RelayEntryOptions, ...RelayEntryOptions[]] }


/**
 * 会话状态快照（design §3.2 对齐子集）。
 * activeEpoch/lastAckAtMs/deadlineAtMs：内核观测未实现，本阶段不投影
 * （不冒充）——随 Phase 4 记账面（task 5.2）补齐。
 */
export interface SessionStateSnapshotJs {
  peerId: string
  /** 会话 id（hex，128bit → 32 字符） */
  sessionId: string
  /** "negotiating" | "active" | "recovering" | "dead" | "closed" */
  phase: string
  streamCount: number
  /** 全部流 journal 持有字节总和（发送侧反压水位观测） */
  journalBytes: number
}
