// napi 生成的 d.ts 后处理：把原生签名改写为 C0 契约形态
// （openspec/changes/hardening-backlog/contracts/client-sdk.d.ts.md，C0.2 增量）。
// index.js 包装层改变了两处可见签名：
//   - on() 原生返回回调 id（number）；包装后返回取消订阅函数 () => void
//   - 事件以 JSON 字符串投递；包装后是类型化事件对象（判别联合）
//
// 结构（9.3）：有序变换管线。每个变换 { name, apply, assertInvariant }：
//   - apply 幂等：目标形态缺失时原样返回（重复运行不重复应用、不破坏）；
//   - 单点断言：锚定改写在应用前检查形态出现次数，>1 处即 throw
//     （napi 输出格式漂移时拒绝盲改），应用后残余由不变量兜底；
//   - 全部变换执行完统一跑 assertInvariant，任一失败即 throw、不落盘写入。
// 变换顺序与历史行为逐语句等价（除 6.1/6.2 新变换）；不引入 AST 依赖。
//
// 6.1/6.2：httpProxy 收敛为唯一 HttpProxyOptions alias 引用，删除 napi 生成的
// HttpProxyUrl interface 块（alias 已完整表达三形态，独立 interface 属冗余契约面）。
// 8.2：注入的 RelayStatusJs 携带 activeUrl: string | null。
// R2 P1-5：relay-options-union 对 NAPI 尾部未知导出 fail-loud（不静默丢弃）；
// inject-event-types 对已注入但模板过期的块整块刷新。
// app-protocol-layer 4.2（2026-09-16）：napi 尾部新增 continuity 导出
// （SessionHandle/HttpServerJs/HttpClientResponseJs/快照/Header/FetchHttpInit）
// ——relay-options-union 从「截断到尾」改为「精确回收 RelayOptions+
// RelayStatusJs 两块、保留其余尾部」；新增 onstate-signature 变换
// （SessionHandle.onState 包装为取消订阅函数，与 on() 同构）。
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

// 可选参数：目标 d.ts 路径（默认包内 index.d.ts），供幂等性/等价性验证使用。
const p = process.argv[2]
  ? path.resolve(process.argv[2])
  : fileURLToPath(new URL("../index.d.ts", import.meta.url));

// 网络磁盘（SMB）页缓存会让文本读拿到旧内容（实证：stat 13559 vs utf8 读 9733，
// 旧缓存被归一化后再写回即产生重复块）。二进制读走不同缓存路径，绕开该问题；
// 写入同样以 Buffer 落盘。
const readDts = () => fs.readFileSync(p).toString("utf8");

/** needle 出现次数（字符串精确匹配） */
function count(s, needle) {
  let n = 0;
  for (let at = s.indexOf(needle); at >= 0; at = s.indexOf(needle, at + needle.length)) {
    n++;
  }
  return n;
}

/**
 * 锚定单点替换：出现 0 次（已应用/不存在）原样返回；1 次替换；
 * >1 次 throw——多目标下盲改会破坏契约，须先确认 napi 格式变化。
 */
function replaceOnce(s, needle, replacement, name) {
  const n = count(s, needle);
  if (n > 1) {
    throw new Error(
      `fix-dts[${name}]: 目标形态出现 ${n} 处（预期 ≤1），napi 输出格式疑似变化，拒绝盲改：${JSON.stringify(needle.slice(0, 60))}`,
    );
  }
  return n === 1 ? s.replace(needle, replacement) : s;
}

/** 事件判别联合 + RelayStatusJs 同构快照注入头（8.2：含 activeUrl） */
const EVENT_TYPES_BLOCK = `/** 事件判别联合：relay-* 事件必携带完整快照 payload（非可选） */
export type FabricEventJs =
  | {
      type: 'peer-connected' | 'peer-disconnected'
      endpointId: string
    }
  | { type: 'roster-updated' }
  | { type: 'message'; from: string; data: Buffer }
  | { type: 'path-changed'; endpointId: string; status: 'direct' | 'relay' | 'unknown' }
  | { type: 'relay-online' | 'relay-offline'; relay: RelayStatusJs }

/** relay 状态快照（relayStatus() 返回值与 relay-* 事件 payload 同构） */
export interface RelayStatusJs {
  /** 字面量联合（非 string） */
  mode: 'disabled' | 'custom' | 'n0'
  /** 配置的 relay URL 列表（disabled 为空数组；n0 为 iroh 上游默认 relay
   *  列表——4 个区域节点，排序冻结；配置原样字符串，R2 P1-4/R3 P1-4） */
  urls: string[]
  /** null <=> mode === "disabled"；否则为任一 relay 已连接 */
  online: boolean | null
  /** 最近一次连接错误类别（脱敏：无凭证段；无错误为 null） */
  lastError: string | null
  /** 配置序最小的已连接 relay URL；online !== true 或 disabled 时为 null。
   *  tie-break：同时连上多个 relay 时取配置序最小者（内核 aggregate_relay_status
   *  既有 online_url 逻辑，无新语义）。 */
  activeUrl: string | null
}

`;

/** 契约形态的 relay 配置（唯一声明，确定性重写 napi 宽松尾部）。
 *  server-access-policy task 2.5：新增 relays 判别分支（per-relay
 *  capability 条目；与 urls 互斥由 native 构造期拒绝）。条目类型
 *  RelayEntryOptions 以 napi 生成的 interface 为契约（同 InviteOptions/
 *  Member 先例），由 relay-options-union 从回收区间携带保留。 */
const RELAY_OPTIONS_UNION = `/** relay 配置（判别联合：非法组合构造期拒绝） */
export type RelayOptions =
  | { mode?: 'n0' }
  | { mode: 'disabled' }
  | { mode: 'custom'; urls: [string, ...string[]] }
  | { mode: 'custom'; relays: [RelayEntryOptions, ...RelayEntryOptions[]] }
`;

/** napi 生成的 HttpProxyUrl interface 块（含前导空行；删除后保留块间单空行） */
const PROXY_URL_BLOCK = `
/** httpProxy 的 \`{ url }\` 形态（"none" | "from-env" 为字符串形态）。 */
export interface HttpProxyUrl {
  url: string
}
`;

/** HttpProxyOptions 公共别名 + deriveErrorCode 声明（P1-3/R3），前置于事件联合 */
const PROXY_ALIAS_BLOCK = `/** 代理策略：none=直连；from-env=读环境代理；url 形态仅 SDK 使用 */
export type HttpProxyOptions = 'none' | 'from-env' | { url: string }

/** 从 SDK 错误消息的 [<kebab-code>] 前缀派生稳定错误码（SCREAMING_SNAKE）；无前缀返回 null */
export declare function deriveErrorCode(message: string): string | null

export type FabricEventJs =`;

const NAPI_MARK = "/* auto-generated by NAPI-RS */";
const HEAD_MARK = "/** 事件判别联合：relay-* 事件必携带完整快照 payload（非可选） */";
const TAIL_MARK = "/**\n * relay 配置（判别联合的 napi 投影）";

/**
 * 变换管线（顺序敏感）。命名与职责：
 * 1. dedupe-normalize        —— 历史重复块归一（napi 块 + 注入头去重）
 * 2. tsfn-callback-void      —— TSFN error-first 回调 any → void
 * 3. on-signature            —— on()：字符串回调 → 类型化事件对象；返回取消订阅函数
 * 4. onstate-signature       —— 4.2：SessionHandle.onState 同构改写（快照回调 + 取消订阅）
 * 5. inject-event-types      —— FabricEventJs + RelayStatusJs（含 activeUrl）注入头
 * 6. http-proxy-alias        —— 6.1/6.2：httpProxy → HttpProxyOptions；删 HttpProxyUrl
 * 7. relay-options-union     —— RelayOptions/RelayStatusJs napi 块精确回收 → 契约判别联合
 *                               （4.2 起 NAPI 尾部有 continuity 导出——保留其余尾部）
 * 8. relay-status-promise    —— index.js 包装 relayStatus 为 async → Promise
 * 9. inject-proxy-alias      —— HttpProxyOptions alias + deriveErrorCode 声明注入
 * 10. truncate-residual-napi —— 终截断：写入前保证 NAPI 标记唯一（脏输入兜底）
 */
const TRANSFORMS = [
  {
    name: "dedupe-normalize",
    // 归一化（幂等前提）：napi 生成块与注入头可能因历史多次运行而重复——
    // 以首个 napi 头为锚，保留其前的注入头一份 + 首个 napi 块，删除后续重复。
    apply(s) {
      if (count(s, NAPI_MARK) > 1) {
        s = s.slice(0, s.indexOf(NAPI_MARK, s.indexOf(NAPI_MARK) + NAPI_MARK.length));
      }
      if (count(s, HEAD_MARK) > 1) {
        // 保留第一份注入头，后续重复块整段删除（含其前导换行）
        const m2 = s.indexOf(HEAD_MARK, s.indexOf(HEAD_MARK) + HEAD_MARK.length);
        s = s.slice(0, m2) + s.slice(m2).split(HEAD_MARK).slice(1).join("").replace(/^\n/, "");
      }
      return s;
    },
    assertInvariant(s) {
      return count(s, NAPI_MARK) === 1 && count(s, HEAD_MARK) <= 1;
    },
  },
  {
    name: "tsfn-callback-void",
    // 全量替换：TSFN 签名中的 => any（当前仅 on 一处；出现多处时逐处归一语义一致）
    apply(s) {
      return s.replaceAll("=> any", "=> void");
    },
    assertInvariant(s) {
      return count(s, "=> any") === 0;
    },
  },
  {
    name: "on-signature",
    apply(s) {
      const re = /on\(callback: [^\n]*\): number/g;
      const matches = s.match(re);
      if (matches && matches.length > 1) {
        throw new Error(`fix-dts[on-signature]: 原生 on() 签名出现 ${matches.length} 处（预期 ≤1），napi 输出格式疑似变化`);
      }
      return s.replace(/on\(callback: [^\n]*\): number/, "on(callback: (event: FabricEventJs) => void): () => void");
    },
    assertInvariant(s) {
      return count(s, "on(callback: (event: FabricEventJs) => void): () => void") === 1;
    },
  },
  {
    name: "onstate-signature",
    // 4.2：index.js 包装 SessionHandle.onState（JSON 字符串回调 → 快照对象；
    // 返回取消订阅函数）。原生形态经 tsfn-callback-void 已是 => void。
    apply(s) {
      return replaceOnce(
        s,
        "onState(callback: ((err: Error | null, arg: string) => void)): number",
        "onState(callback: (state: SessionStateSnapshotJs) => void): () => void",
        "onstate-signature",
      );
    },
    assertInvariant(s) {
      return (
        count(s, "onState(callback: (state: SessionStateSnapshotJs) => void): () => void") === 1 &&
        count(s, "offState(id: number): void") === 1
      );
    },
  },
  {
    name: "inject-event-types",
    // 已注入但模板演进（如注释修正）时整块刷新：块范围 = HEAD_MARK 起至
    // NAPI 标记前（注入头永远位于 napi 生成块之前）；不存在则前置注入。
    apply(s) {
      if (!s.includes("export type FabricEventJs")) {
        return EVENT_TYPES_BLOCK + s;
      }
      const start = s.indexOf(HEAD_MARK);
      if (start < 0) return s;
      const end = s.indexOf(NAPI_MARK, start);
      if (end < 0) return s;
      const current = s.slice(start, end);
      return current === EVENT_TYPES_BLOCK ? s : s.slice(0, start) + EVENT_TYPES_BLOCK + s.slice(end);
    },
    assertInvariant(s) {
      return count(s, "export type FabricEventJs") === 1 && count(s, "export interface RelayStatusJs") === 1;
    },
  },
  {
    name: "http-proxy-alias",
    // 6.1/6.2：三种历史形态统一收敛为 alias 引用（幂等，重复运行零匹配零应用）
    apply(s) {
      // napi 原生形态：Either<String, HttpProxyUrl>
      s = replaceOnce(s, "httpProxy?: string | HttpProxyUrl", "httpProxy?: HttpProxyOptions", "http-proxy-alias");
      // 历史产物形态（fix-dts 旧版的内联联合）
      s = replaceOnce(
        s,
        "httpProxy?: 'none' | 'from-env' | { url: string }",
        "httpProxy?: HttpProxyOptions",
        "http-proxy-alias",
      );
      // napi 生成的 HttpProxyUrl interface 块整块删除（6.2）
      s = replaceOnce(s, PROXY_URL_BLOCK, "\n", "http-proxy-alias");
      return s;
    },
    assertInvariant(s) {
      return count(s, "httpProxy?: HttpProxyOptions") === 1 && count(s, "HttpProxyUrl") === 0;
    },
  },
  {
    name: "relay-options-union",
    // 唯一声明（P1-1，确定性重写）：精确回收 napi 生成的 RelayOptions +
    // RelayStatusJs 块，原位替换为契约判别联合。4.2 起 NAPI 尾部还有
    // continuity 导出（SessionStateSnapshotJs 等）——必须保留。
    // task 2.5：RelayEntryOptions / RelayCapabilityJs（napi 生成顺序不保证
    // 落点）落在回收区间内时携带保留（napi interface 即契约形态，同
    // InviteOptions/Member 先例）；区间外的落点不受影响。区间内出现家族
    // 之外的任何顶层声明仍 fail-loud（napi 输出格式变化时拒绝盲改）。
    apply(s) {
      if (count(s, TAIL_MARK) > 1) {
        throw new Error(`fix-dts[relay-options-union]: 尾部标记出现 ${count(s, TAIL_MARK)} 处（预期 ≤1）`);
      }
      const tailStart = s.indexOf(TAIL_MARK);
      if (tailStart < 0) return s; // 已是契约形态（重跑）
      const ifaceStart = s.indexOf("export interface RelayStatusJs", tailStart);
      if (ifaceStart < 0) {
        throw new Error("fix-dts[relay-options-union]: RelayStatusJs 接口未找到（napi 输出形态变化）");
      }
      // 花括号配平扫描找 RelayStatusJs 块结束
      let depth = 0;
      let end = -1;
      for (let i = s.indexOf("{", ifaceStart); i < s.length; i++) {
        if (s[i] === "{") depth++;
        else if (s[i] === "}") {
          depth--;
          if (depth === 0) {
            end = i;
            break;
          }
        }
      }
      if (end < 0) {
        throw new Error("fix-dts[relay-options-union]: RelayStatusJs 块未配平（拒绝盲改）");
      }
      let cutEnd = end + 1;
      if (s[cutEnd] === "\n") cutEnd++;
      const region = s.slice(tailStart, cutEnd);
      const declRe = /\nexport\s+(?:interface|type|class|const|function|declare\s+\w+)\s+(\w+)/g;
      const found = new Set();
      for (let m = declRe.exec(region); m !== null; m = declRe.exec(region)) {
        found.add(m[1]);
      }
      // task 2.5：家族成员白名单 + 携带集合（联合模板不重复声明它们——
      // napi interface 形态即契约，落点在区间内则原块保留）
      const CARRY = ["RelayEntryOptions", "RelayCapabilityJs"];
      for (const name of found) {
        if (name !== "RelayOptions" && name !== "RelayStatusJs" && !CARRY.includes(name)) {
          throw new Error(
            `fix-dts[relay-options-union]: 回收区间出现未知导出 ${name}` +
              "（区间形态变化，拒绝盲改；新导出应保留在尾部——检查 TAIL_MARK/块边界逻辑）",
          );
        }
      }
      if (!found.has("RelayOptions") || !found.has("RelayStatusJs")) {
        throw new Error(
          "fix-dts[relay-options-union]: 回收区间缺少预期的 RelayOptions/RelayStatusJs（napi 输出形态变化）",
        );
      }
      // 提取携带成员的完整块（前导 doc 注释 + 接口体；顺序固定）
      const carried = [];
      for (const name of CARRY) {
        if (!found.has(name)) continue;
        const declAt = region.indexOf(`export interface ${name}`);
        // 前导 /** ... */（紧邻才算，避免吞掉上一块的尾注）
        let start = declAt;
        const before = region.slice(0, declAt);
        const docEnd = before.lastIndexOf("*/");
        if (docEnd >= 0 && /^\s*$/.test(region.slice(docEnd + 2, declAt))) {
          const docStart = before.lastIndexOf("/**", docEnd);
          if (docStart >= 0) start = docStart;
        }
        let d = 0;
        let e = -1;
        for (let i = region.indexOf("{", declAt); i < region.length; i++) {
          if (region[i] === "{") d++;
          else if (region[i] === "}") {
            d--;
            if (d === 0) {
              e = i;
              break;
            }
          }
        }
        if (e < 0) {
          throw new Error(`fix-dts[relay-options-union]: ${name} 块未配平（拒绝盲改）`);
        }
        carried.push(region.slice(start, e + 1).trimEnd());
      }
      const carryText = carried.length ? "\n\n" + carried.join("\n\n") + "\n" : "\n";
      return (
        s.slice(0, tailStart) +
        RELAY_OPTIONS_UNION.trimEnd() +
        "\n" +
        carryText +
        s.slice(cutEnd)
      );
    },
    assertInvariant(s) {
      return (
        count(s, "export type RelayOptions") === 1 &&
        count(s, "export interface RelayOptions") === 0 &&
        count(s, "export interface RelayEntryOptions") === 1 &&
        count(s, "export interface RelayCapabilityJs") === 1 &&
        count(s, "relays: [RelayEntryOptions, ...RelayEntryOptions[]]") === 1 &&
        !s.includes(TAIL_MARK)
      );
    },
  },
  {
    name: "relay-status-promise",
    // index.js 包装为 async → Promise（P1-1）
    apply(s) {
      return replaceOnce(s, "relayStatus(): RelayStatusJs", "relayStatus(): Promise<RelayStatusJs>", "relay-status-promise");
    },
    assertInvariant(s) {
      return count(s, "relayStatus(): Promise<RelayStatusJs>") === 1;
    },
  },
  {
    name: "inject-proxy-alias",
    // P1-3（R3）：导出 HttpProxyOptions 公共别名 + deriveErrorCode 声明
    apply(s) {
      if (s.includes("export type HttpProxyOptions")) return s;
      return replaceOnce(s, "export type FabricEventJs =", PROXY_ALIAS_BLOCK, "inject-proxy-alias");
    },
    assertInvariant(s) {
      return (
        count(s, "export type HttpProxyOptions") === 1 &&
        count(s, "deriveErrorCode(message: string): string | null") === 1
      );
    },
  },
  {
    name: "truncate-residual-napi",
    // 终截断：注入/变换可能重新引入 NAPI 标记重复（注入头本身不含，但历史运行
    // 的脏输入会），写入前最后执行一次位置截断保证唯一。
    apply(s) {
      const first = s.indexOf(NAPI_MARK);
      if (first < 0) return s;
      const second = s.indexOf(NAPI_MARK, first + NAPI_MARK.length);
      if (second < 0) return s;
      return s.slice(0, second).trimEnd() + "\n";
    },
    assertInvariant(s) {
      return count(s, NAPI_MARK) === 1;
    },
  },
];

let s = readDts();
for (const t of TRANSFORMS) {
  s = t.apply(s);
}
const failed = TRANSFORMS.filter((t) => !t.assertInvariant(s)).map((t) => t.name);
if (failed.length > 0) {
  throw new Error(`fix-dts: 输出不变量失败（未写入）：${failed.join(", ")}`);
}
fs.writeFileSync(p, Buffer.from(s, "utf8"));
console.log("index.d.ts fixed");
